### ISSUE TITLE
Message Factory update for phase 1

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#28]
Support "execute" message type.

**Comment by shumy** [comment]
@acheambe Using the model defined in [Message Model](https://github.com/reTHINK-project/dev-service-framework/tree/develop/docs/datamodel/message)  how do I set the optional fields in the MessageBody?
Subscribe message has some changes, can you update to be complient with the model?

**Comment by shumy** [comment]
At the moment to set a optional field I have to, for example: msg.body.resource = x;
Using the "body", is no different from setting a JSON object, it has an inner line dependency of the JSON structure!

**Comment by acheambe** [comment]
@shumy i will update the Subscirbe message to reflect the new spec.

Regarding setting the optional fields, yes you can use the above described procedure. Or i could add setters to the fields. Which do you prefer?

**Comment by acheambe** [comment]
Support "execute" message type has been added to the MessageFactory
