### ISSUE TITLE
Update from one distribution file to multiple

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-service-framework#29]
With the objective to optimize the distribution file on dev-service-framework, we do some changes in the way how the file will be distributed;

At this moment, we have only one distribution file and aggregate all the src code inside of it;

After this optimization we will have on file for each module example.

How to import in the **New Way**;

To import the dev-service-framework modules now you need to do:
```javascript
// This is the default class exported;
import CatalogueFactory from 'service-framework/dist/CatalogueFactory';

// This is the other classes exported
import {HypertyDescriptor, ProtocolStubDescriptor, SourcePackage} from 'service-framework/dist/CatalogueFactory';

// or
import MessageFactory from 'service-framework/dist/MessageFactory';

// or
import {Syncher, DataObjectReporter, DataObjectObserver} from 'service-framework/dist/Syncher';

```
I recommend all developers which have a module in [dev-runtime-core](), [dev-browser-runtime]() or another repository, which use an dependency from dev-service-framework, update to the new way of import modules;

if you detect something is not right, please fix or open an issue

**Comment by pchainho** [comment]
Missing, pls open issues to address this:
@gamdias (Runtime Registry; Id Module)
@shumy (Sync Manager)
@AnaSLCaldeira (Policy Engine)
