### ISSUE TITLE
Add HelloWorld entries to catalogue

### ISSUE THREAD

**Issue by emmelmann-fokus** [reTHINK-project/dev-service-framework#30]
Once HelloWorld Hyperty has reached maturity,

all information that is required to be provided from the Catalogue should be added to 

https://github.com/reTHINK-project/dev-catalogue/tree/master/catalogue_objects

This will assure that the required catalogue entries are by default included in the "out-of-the-box" catalogue test installation.  This will also assure that the helloWorld related info will be permanently accessible via the catalogue instance running at fokus (and that is accessible from all testbeds).

**Comment by pchainho** [comment]
This was done

**Comment by emmelmann-fokus** [comment]
@pchainho, just reopening this issue to sync with you.

I checked the master and the dev branch but cannot see the integrated hyperty code.  Maybe a push was missing?

Please check.

Best,

M.
