### ISSUE TITLE
Catalogue (Factory) update

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#34]
As discussed [here](https://github.com/reTHINK-project/dev-registry-domain/issues/8) searches in the runtime registry are currently very limited and don't support Hyperty searches per type.

A minor update in the catalogue data model is proposed:

- In [Hyperty Descriptor](https://github.com/reTHINK-project/dev-service-framework/blob/develop/docs/datamodel/core/hyperty-catalogue/readme.md#hyperty-descriptor) HypertyType is updated to be an array of HypertyResourceType objects
- In [DataObjectScheme](https://github.com/reTHINK-project/dev-service-framework/blob/develop/docs/datamodel/core/hyperty-catalogue/readme.md#data-object-schema) add a new "scheme" attribute.

@emmelmann-fokus , @acheambe ?

**Comment by acheambe** [comment]
opps! posted of wrong issue thread. 
Here is it again, on the right thread.

@pchainho 
the HypertyType use to be represented by either the following HypertyTypes (Comunicator, Identity or context).
If i get you right, the HypertyType should now be represented as an array of HypertyResourceType. I can not find anywhere the specification of the HypertyResourceType. Can you give me a pointer pls? 
Or do you mean an array of HypertyTypes?

**Comment by pchainho** [comment]
The HypertyResourceType is defined in the [Hyperty Descriptor](https://github.com/reTHINK-project/dev-service-framework/blob/develop/docs/datamodel/core/hyperty-catalogue/readme.md#hyperty-descriptor) model but the textual description was not updated yet

**Comment by acheambe** [comment]
ah, now i see it. Maybe the text could later be updated too, just for global understanding. the model pictures no longer match the written texts. 

so instead of hypertyDescriptor.hypertyType = communicator it is now
hypertyDescriptor.hypertyType = [ a, ..z] where [a,...z] : {audio, video, chat, screen, av, midi, file }

got it.

**Comment by acheambe** [comment]
Changes commited on develop branch. 
https://github.com/reTHINK-project/dev-service-framework/commit/a109168170bf1be5090d61f9321eeef2b24af5e1 and https://github.com/reTHINK-project/dev-service-framework/commit/3452acd536e3ef2a39a55bae48179c438f4cea2a
please check your implementations if all is working as previewed.

I will leave this thread open on which to report any problems with these extensions. Will close it mid next week if no problems.

**Comment by acheambe** [comment]
No issues reported so far from the update. Considering task done. Closing...
