### ISSUE TITLE
Discovery: Hyperty instance search by data scheme and resource type

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#36]
Support Hyperty instance search as agreed [here](https://github.com/reTHINK-project/dev-registry-domain/issues/8) using as criteria supported resources and dataSchemes. Proposal:

`discoverHyperty(Identity.identifier userIdentifier, URL.DomainURL userDomain[], string dataSchemes[], HypertyResourceType[])`

**Comment by gamdias** [comment]
Method supported in the discovery Lib.
 https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/discovery/Discovery.js
