### ISSUE TITLE
Provisioning of the Data Object schemas in the Catalogue

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#38]
https://github.com/reTHINK-project/dev-service-framework/tree/master/schemas/json-schema/data-objects

**Comment by acheambe** [comment]
@vitormsilva when will the schemas be available on the catalogue so i can proceed with this https://github.com/reTHINK-project/dev-service-framework/issues/11

Is the provisioning manual? Or via the runtime?
br
Alice

**Comment by Endebert** [comment]
Will the schemas be revised at some point? Many parts of them seem to be faulty, and e.g. context is supposed to be compliant with https://tools.ietf.org/html/draft-jennings-core-senml-01, but from what I can tell, it is not.

**Comment by vitormsilva** [comment]
@acheambe, The schemes are available on both catalogues (local and remote).
The remote-catalogue is located on [dev-catalogue](https://github.com/reTHINK-project/dev-catalogue/tree/master/docker/catalogue-database-reTHINKdefault/catalogue_objects/dataschema) to install through the dockerfile.

**Comment by acheambe** [comment]
thx for the update @vitormsilva. I will take a look at it. As @Endebert pointed out and from this discussion https://github.com/reTHINK-project/dev-service-framework/issues/41, changes might have to be done. however, i will go ahead and test the other schemes.

**Comment by vitormsilva** [comment]
The schemas on catalogue have been updated with this last version;
Closing;
