### ISSUE TITLE
Update Service Framework docs for the toolkit

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#40]

**Comment by acheambe** [comment]
can you also reference which part of the documentation (not the api docs) md files, you want reviewed?

**Comment by pchainho** [comment]
This [readme](https://github.com/reTHINK-project/dev-service-framework/blob/develop/README.md) should be updated taking into account that tutorials and quick guide are now in [toolkit repo](https://github.com/reTHINK-project/dev-service-framework/blob/develop/README.md)

**Comment by acheambe** [comment]
Done. 
I find the documentation still very distributed across multiple repositories. This is merely a suggestion. How about aggregating all necessary documentation for developers in one repository and have [readthedocs](https://readthedocs.org/) generate a single paged documentation necessary for developers. Could be useful for the friendly-trial-developers and later for the Hackathon.
