### ISSUE TITLE
Doubts about the correctness of the data models

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-service-framework#41]
For example, relating to the Context Data Object Model:
- Why is there a  field called "value", if it is a list of values?
- On the other hand, why is there a field called "units", if it is just one unit?
- Where is ContextUnit, RawContextValue and ProcessedContextValue defined?
- The Actions object has "type : Action", but where is Action defined?
- In Context I can only specify that there are "actions" or "contexts" children, but I can't define what they are called?
- Why is there a thing called "sum" in ContextValue if it doesn't represent anything?
- Where is the type "URL.HypertyRuntimeURL" defined?

**Comment by pchainho** [comment]
thx @Endebert, I've just updated the model according to your feedback.

More below:

> The Actions object has "type : Action", but where is Action defined?

The "Action" class is defined in the diagram

> In Context I can only specify that there are "actions" or "contexts" children, but I can't define what they are called?

Not clear: what do you mean by "define what they are called"?

> Where is the type "URL.HypertyRuntimeURL" defined?

Is defined [here](https://github.com/reTHINK-project/dev-service-framework/blob/develop/docs/datamodel/core/address/readme.md)

**Comment by Endebert** [comment]
Thanks for the update. Sorry about the Action class, I must have overlooked it.

Regarding the children field, if I provide it, it seems it has to be like `'children': ['actions', 'contexts']`, but shouldn't its value be a list of enumerations or something like that? This also implies I either have no children at all, or both actions and contexts. Even still, there is no way to actually attach the actions objects to the context. The closest I could find in the [Sync Data Object Model](https://github.com/reTHINK-project/dev-service-framework/tree/develop/docs/datamodel/data-objects/data-synch), but even there you can't attach them. Shouldn't there be a field like `"childen": SyncObjectChild[]`? (In SyncDataObject I can see that in the SyncObjectParent class, "children" is defined as a list of Strings, but then the image implies it should be a list of SyncObjectChildren. And SyncObjectChildren has the type SyncObjectChild, which also doesn't seem right. This would imply that those children are all identical to each other).

Also it would be great if externally defined classes would be linked for easy reference, instead of having to sift through all the folders to find them.

**Comment by pchainho** [comment]
> Regarding the children field, if I provide it, it seems it has to be like 'children': ['actions', 'contexts'], but shouldn't its value be a list of enumerations or something like that? This also implies I either have no children at all, or both actions and contexts.

I'll check with @shumy but I suspect we need children definition in this way

> Even still, there is no way to actually attach the actions objects to the context. The closest I could find in the Sync Data Object Model, but even there you can't attach them.

yes, there is no composition relationship between Parent and Children. This is because only a single Hyperty Instance (the Parent Reporter) has permissions to write in the Parent object.

> In SyncDataObject I can see that in the SyncObjectParent class, "children" is defined as a list of Strings, but then the image implies it should be a list of SyncObjectChildren.

No, "children" is the list of children class names not capitalized. The class diagram expresses there is a one to many association between the Parent and the Children, but this association is not Composition. 

 > And SyncObjectChildren has the type SyncObjectChild, which also doesn't seem right. This would imply that those children are all identical to each other.

humm probably you are right! It should be a constant with the name of the Child classname, instead. I'll check with @shumy if this change has no impact in the implementation

> Also it would be great if externally defined classes would be linked for easy reference, instead of having to sift through all the folders to find them

agree

**Comment by Endebert** [comment]
> yes, there is no composition relationship between Parent and Children. This is because only a single Hyperty Instance (the Parent Reporter) has permissions to write in the Parent object.

But then how can I provide information about what actions the hyperty supports? Let's say I have a hyperty that represents a room, and a Context that represents a light in that room. Now I want to provide some information about the actions this light supports. For example, I thought that I could say something like `children: ["setState", "setBrightness"]` but this seems to be not the case. All I can say is `children["actions", "contexts"]` even though the light doesn't have child contexts, and how is another hyperty supposed to know what actions it supports? Is there no way to provide a list of supported actions?

By the way, from an implementation perspective, I find it strange that the observer hyperty has to add the (action) child, instead of the reporter hyperty. This means that an observer hyperty can add whatever actions it wants to the parent object, and can't know if the action is actually supported or not. (At least that is my understanding on how it is supposed to be done).

Compare this to how this is handled in the Communication Data Model, where children is defined as `children = ["chatmessages"]`.

> No, "children" is the list of children class names not capitalized. The class diagram expresses there is a one to many association between the Parent and the Children, but this association is not Composition.

But based on the class diagram it is impossible to know what this string array is supposed to contain. It implies an association, but not how specifically.
Similarly, in the same diagram there is a one to many association between SyncObjectChildren and SyncObjectChild, which I guess is for the field `childrenUrls`, and here it actually states that this association is based on `ChildId`.
Now, there are several problems with this. First, it is a one to many association, but childrenUrls is an optional field, so doesn't that imply a zero to many association? Also, ChildId does not exist in SyncObjectChild. Even still, if the `childrenUrls` is an array of URLs, shouldn't the association be based on the `url` field (that is defined in SyncObject)?

**Comment by Endebert** [comment]
To add to the list of problems with Data Models:

1. According to the diagram, Context class is derived both from SyncObjectChild and SyncObjectParent. This is bad practice and should be avoided, besides not even being possible in some programming languages.

2. The `type` field in SyncObjectChildren is defined as `type: string`. Yet in the Contexts class, that is derived from SyncObjectChildren, the definition is `type: Context`.

**Comment by pchainho** [comment]
> But then how can I provide information about what actions the hyperty supports? Let's say I have a hyperty that represents a room, and a Context that represents a light in that room. Now I want to provide some information about the actions this light supports. For example, I thought that I could say something like `children: ["setState", "setBrightness"]` but this seems to not be the case. 

You can! pls note that the idea is to extend the Context model to your scenario. You can add different "Childrens", one per each sensor and actuator in the room. However, I suspect your "setState" (room occupancy?) could be support by just an attribute in the "Room" data object. It would be useful to start designing the Room data model. If you provide me the types of sensors, atuators and data you want to address, I could try to propose something.

> ... and how is another hyperty supposed to know what actions it supports? Is there no way to provide a list of supported actions?

The Data Object schema descriptor should provide all this information by providing a JSON Schema class per Actuator (extension of "Action") and per Sensor (extension of "Context").

> By the way, from an implementation perspective, I find it strange that the observer hyperty has to add the (action) child, instead of the reporter hyperty. This means that an observer hyperty can add whatever actions it wants to the parent object, ...

Shouldn't be strange. The Room Observer Hyperty requests the Room Reporter Hyperty to perform some actions on the Room Actuators. The Room Reporter Hyperty should be able to reject these requests

> ... and can't know if the action is actually supported or not. (At least that is my understanding on how it is supposed to be done).

See above. Observers can know supported Actions from the Data Object Schema descriptor.

> Compare this to how this is handled in the Communication Data Model, where children is defined as children = ["chatmessages"]. In code (observer side) you would do addChild("chatmessages", obj). So I would have to add a child called "actions", and add an Action(s) object, but I can't ever know if this Action(s) object will ever be handled by the reporter hyperty that listens via onAddChild(), because it may not support the Action that I added. And since this is no request->reply procedure, there is no feedback for the observer side.

As mentioned above, you can add one "children" per atuator and sensor, each one described by a json-schema class.

> But based on the class diagram it is impossible to know what this string array is supposed to contain. It implies an association, but not how specifically.

This should be now clarified. But let me know if further clarification is required.

> Similarly, in the same diagram there is a one to many association between SyncObjectChildren and SyncObjectChild, which I guess is for the field childrenUrls, and here it actually states that this association is based on ChildId. Now, there are several problems with this. First, it is a one to many association, but childrenUrls is an optional field, so doesn't that imply a zero to many association? 

The association between SyncObjectChildren and SyncObjectChild can be provided in the Data Object itself by the "childrenUrls" attribute. If this attribute is not present, the association still exists but has to be handled by the Hyperty itself. This is for optimisation purposes. In case the "childrenUrls" attribute exists, this means everytime there is a new Child, all the observers would receive a notification about this change in the Parent Reporter, and in many use cases this would be over kill.

> Also, ChildId does not exist in SyncObjectChild. 

the ChildId is "SyncObjectChild.url"  

> Even still, if the childrenUrls is an array of URLs, shouldn't the association be based on the url field (that is defined in SyncObject)?

not sure about what you are proposing here, but I suspect that is what we are doing ie the "SyncObjectChild.url"  is an element of "childrenUrls" array when present.

**Comment by pchainho** [comment]
> According to the diagram, Context class is derived both from SyncObjectChild and SyncObjectParent. This is bad practice and should be avoided, besides not even being possible in some programming languages.

yes, but this is just for data model purposes. You don't have to implement this in javascript

> The type field in SyncObjectChildren is defined as type: string. Yet in the Contexts class, that is derived from SyncObjectChildren, the definition is type: Context. I can see in the last commit that changed that image, you changed the type to string, but only in Actions, not in Contexts.

yes, I've missed that one. Already fixed.

**Comment by Endebert** [comment]
> You can! pls note that the idea is to extend the Context model to your scenario. You can add different "Childrens", one per each sensor and actuator in the room. 

I can't change the "children" field anymore because it is set to "['actions', 'contexts']". If I would extend the model and change the value of children field, it wouldn't be in compliance with the model anymore. Of course I could make my own schema, but I thought the point is to be in compliance with the Context Data Model.

Maybe it would be best if you would just provide me with a proper json schema that I'm supposed to use. Based on that, I could then add my own extensions to it.

> However, I suspect your "setState" (room occupancy?) could be support by just an attribute in the "Room" data object. It would be useful to start designing the Room data model. If you provide me the types of sensors, atuators and data you want to address, I could try to propose something.

I thought I should implement it in a way that a hyperty represents a room and its data objects represent the devices in that room?

> Shouldn't be strange. The Room Observer Hyperty requests the Room Reporter Hyperty to perform some actions on the Room Actuators. The Room Reporter Hyperty should be able to reject these requests

It is currently not possible to reject added children. At least I couldn't find a way to do that. If it is indeed possible, please provide me with a code example.

**Comment by Endebert** [comment]
In regards to:

> You can! pls note that the idea is to extend the Context model to your scenario. You can add different "Childrens", one per each sensor and actuator in the room.

I did some basic testing to see if this way of implementing it is actually possible, but unfortunately, that does not seem to be the case.

Let's say my reporter hyperty creates a Room object (of type Context), and adds a Light object (of type Context) as a child using `roomObj.addChild()`. Now from what I can tell, after the observer hyperty subscribed to the Room object, I believe it is able to get access to the Light object, but this object does not have a `addChild()` function, so I can't add an Action object to it.

This raises the question: How can an observer hyperty, i.e. a hyperty that subscribed to a Context object, add a child object to a child of that subscribed Context object.

As a more visual representation, this is what I want to achieve:
```
Room (Context)
└─ Light (Context as Child)
   └─ setBrightness (Action) <- How do I add this action?
```

**Comment by pchainho** [comment]
One possible example for a Room Context JSON Data Object with current light value (in case we have a sensor for light).

```javascript
{
"name": 'room 305'
"url": 'context://cozy-hotel.com/room305'
"scheme": "context",
 "time": 1465070579,
 "values": [ {"name": "lumen", "unit": "lm", "value": 800 } ],
 "children": ["set-brightness-actions"]
  }
```

One possible example for a Child Action JSON Object added to `set-brightness-actions` children to setBrightness in the Room

```javascript
{
 "values": [ {"type": "light", "name": "lumen", "unit": "lm", "value": 200 } ]
  }
```

In this example I've skipped the Light Context object since the actuator can be directly related with the Room object and it will simplify the model.

**Comment by Endebert** [comment]
That wouldn't work at all, a room could have many lights. And I don't want to invoke an action on the room, I want to invoke an action on a device.

And it wouldn't be compliant with the data model, because the "children" property is a constant and can't be changed anymore.

So I can't have a context object as a child of another context object?

**Comment by pchainho** [comment]
Ok, in that case we would have a context object data for each light and add them as childs
to the Room Context JSON Data Object. 

```javascripto
{
"name": 'Room305'
"url": 'context://cozy-hotel.com/room305'
"scheme": "context",
 "time": 1465070579,
 "chilUrls": ["context://cozy-hotel.com/light3051"]
  }
```

One possible example for one light object featuring an actuator to set brightness

```javascript
{
"name": 'Light3051'
"url": 'context://cozy-hotel.com/light3051'
"scheme": "context",
 "time": 1465070579,
 "values": [ {"name": "lumen", "unit": "lm", "value": 800 } ],
 "children": ["set-brightness-actions"]
  }
```

Pls note that in this case the light object does not belong to any children collection and we don't use addChild(..) to add it to the parent, but you just push its URL to parent.childUrls array.

One possible example for a Child Action JSON Object added to `set-brightness-actions` children to setBrightness to the light.

```javascript
{
 "values": [ {"type": "light", "name": "lumen", "unit": "lm", "value": 200 } ]
  }
```

**Comment by pchainho** [comment]
I understand this has been clarified. we'll reopen it if needed

**Comment by Endebert** [comment]
Reopening this until issue https://github.com/reTHINK-project/dev-service-framework/issues/53 is resolved.

I'm also using this issue to post questions/remarks regarding the data model.


Regarding the [Sync Data Object Model](https://github.com/reTHINK-project/dev-service-framework/tree/develop/docs/datamodel/data-objects/data-synch):

1. Why do we need SyncObjectChildren?

    I do not understand the need to have this class. If a SyncObjectParent can already hold multiple SyncObjectChild objects, why do we need another class that does the same? If the only reason is the added information contained in SyncObjectChildren, why not move this information into SyncObjectParent? I suggest to either do that, or remove the ability for the SyncObjectParent to hold SyncObjectChild objects.

2. Change the name of SyncObjectChildren

   This was a bad idea and has already lead to much confusion. The purpose of this class is to hold (references of) multiple SyncObjectChild objects, so it should be renamed to SyncObjectChildHolder or something similar.

**Comment by pchainho** [comment]
> Why do we need SyncObjectChildren?

> I do not understand the need to have this class. If a SyncObjectParent can already hold multiple SyncObjectChild objects, why do we need another class that does the same? If the only reason is the added information contained in SyncObjectChildren, why not move this information into SyncObjectParent? I suggest to either do that, or remove the ability for the SyncObjectParent to hold SyncObjectChild objects.

A SyncObjectChildren is a container of SyncObjectChild of the same type, but one SyncObjectParent may have more than one containers of SyncObjectChild. But probably you are right, and we can remove "childUrls" attribute from "SyncObjectParent".

> Change the name of SyncObjectChildren

> This was a bad idea and has already lead to much confusion. The purpose of this class is to hold (references of) multiple SyncObjectChild objects, so it should be renamed to SyncObjectChildHolder or something similar.

I'm ok with this change. SyncObjectChildContainer is also an alternative. However, we should keep using the "/children" string in the URL path of SyncObjectParent data objects.

**Comment by Endebert** [comment]
Since we're nearing the end of the project, I'm closing all spec related issues, like this one.
