### ISSUE TITLE
Doubts about the correctness of the json schemas

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-service-framework#42]
This is also in reference to the issue with the data models: https://github.com/reTHINK-project/dev-service-framework/issues/41

For example, the schema for [HypertyResourceType](https://github.com/reTHINK-project/dev-service-framework/blob/master/schemas/json-schema/data-objects/HypertyResource.json) is not very sensible. Let's say I want to define a HypertyResource, it would have to look like this in order to comply with the schema:

```
let myResource = {
    "type": {"CHAT": null, "AUDIO": null, "VIDEO": null, "AV": null, "SCREEN": null, "FILE": null, "MIDI": null}
}
```

This is just an example, and this issue is a request to refactor (at least) HypertyResource.json and Context.json (these are the ones I looked at).

**Comment by pchainho** [comment]
Hi, the HypertyResourceType should be an enum. I'll update the model.

**Comment by pchainho** [comment]
This should be fixed now. Reopen if needed

**Comment by Endebert** [comment]
Now that I've implemented object validation against schemas, I'm reading more about how json schemas have to be defined, and while extending tests to include validation of several object types, I've noticed that basically all of the json schemas in this repository need to be reworked. 

Some examples:

* "id" field in every schema is not a valid URI
* Message.json/MessagBody and its subclasses are defined the opposite way they should be
* RegistryDataObject.json and its subclasses are defined the opposite way they should be
* RethinkCore.CatalogueDataObject.json and its subclasses are defined the opposite way they should be
* RethinkCore.CatalogueDataObject.json/CatalogueObjectType has the same problem I have already pointed out for the HypertyResourceType
* Identity.json/ServiceType has the same problem I have already pointed out for the HypertyResourceType
* subclasses of RethinkCore.CatalogueDataObject.json lack some important specifications (e.g. HypertyDescriptor has to have CatalogueObjectType "hyperty")
* URL.json is basically not defined at all, lacks subclasses, etc.
* many local and external references are wrong

Instead of writing down every problem, I will do this myself now. I was hoping that because of this issue someone would have checked all the schemas for correctness. I guess I should have have been more explicit in my initial comment.

**Comment by pchainho** [comment]
We haven't had the chance to look on this carefully and your help is appreciated.

You should note that json-schemas were generated from [plantuml](http://plantuml.com/) defined [here (core)](https://github.com/reTHINK-project/dev-service-framework/tree/develop/schemas/core) and [here(data objects)](https://github.com/reTHINK-project/dev-service-framework/tree/develop/schemas/data-objects) using this [tool](https://github.com/reTHINK-project/dev-service-framework/tree/develop/tools/plantuml-json-parser).

As far as I know the "data-objects" schemas were fully generated with this tool with no problem and the syntax should be correct. However we had some problems with the "core" plantuml files that prevented to fully generate the corresponding json-schema files.

**Comment by emmelmann-fokus** [comment]
Just a quick comment from the off (sorry, still traveling):  if the used toolchain does not produce a standard-compliant schema, we'll either have to agree to abandon the toolchain or not to verify the generated object.  We did not calculate the resources to recursively verify created objects.

@Endebert is kind enough to fix potential issue once, but once this has been initially done, the project as a whole need to take over.

**Comment by pchainho** [comment]
Hi Marc, the "toolchain" works fine for "data objects" schema and should work fine for the most relevant schemas in the core model including the "URL". For the ones that does not work I would suggest not to use the json-schema generator tool.

**Comment by Endebert** [comment]
The provided plantuml-json-parser does not create json schemas that are good enough to be used for validation purpuses, and the current state of the schemas is also not acceptable. 

Let's take the current schema for URL as an example. If I parse the current schema from the develop branch, I get this json schema:
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",

	"id": "URL",
	"type": "object",
	"required": ["scheme"],
	"anyOf": [
		{ "type": "string" },
		{ "type": "string" },
		{ "type": "string" },
		{ "type": "string" },
		{ "type": "string" },
		{ "type": "string" },
		{ "type": "string" },
		{ "type": "string" },
		{ "type": "string" },
		{ "type": "string" }
	]
	,
	"properties": {
		"scheme": {
			"type": "string"
		},
		...
	}, 
	"UserURL": {
		"type": "object",
		"required": ["scheme"],
		"properties": {
			"scheme": {
				"constant": "user"
			}
		}
	}, 
	...
}
```
As you can see, the `anyOf` attribute of URL is a mess, and UserURL lacks an `anyOf` attribute to make clear that it is a subclass of URL.

Now look at the resulting image:
![image](https://cloud.githubusercontent.com/assets/9431420/17330260/72c75870-58c6-11e6-9814-b5168d7fbc7e.png)

The arrows from the subclasses to the URL class are broken.


The source of the Problem is that in the original schema file, the Rect surrounding the classes has the same name as the URL class it encapsulates:

```
package URL <<Rect>> {

	class URL <<(T,orchid)>> {
		scheme : string
		username? : string
		password? : string
		host? : string
		port? : string
		path? : string
		query? : string
		fragment? : string
	}
	...
}
```
This is the image when I change the name of the Rectangle:

![image](https://cloud.githubusercontent.com/assets/9431420/17330333/c6878282-58c6-11e6-9d82-02265d4d517e.png)

The image is now properly generated. But what does that mean for the json schemas? This is the new result.

1. there is now a SomeOtherName.json that looks like what URL.json looked like before the change
2. URL.json now looks like this
    ```
	{
		"$schema": "http://json-schema.org/draft-04/schema#",

		"URLList": {
			"type": "object",
			"anyOf": [
				{ "$ref": "#/UserURLList" },
				{ "$ref": "#/UserUUIDURLList" },
				{ "$ref": "#/UserAccountURLList" },
				{ "$ref": "#/HypertyURLList" },
				{ "$ref": "#/HypertyCatalogueURLList" },
				{ "$ref": "#/HypertyRuntimeURLList" },
				{ "$ref": "#/CommunicationURLList" },
				{ "$ref": "#/DomainURLList" },
				{ "$ref": "#/ContextURLList" }
			]
			,
			"properties": {
			}
		}, 
		"UserURLList": {
			"type": "object",
			"properties": {
			}
		}, 
		...
	}
    ```
Now Lists are defined, the anyOf attribute of URLList now makes more sense, but there are no properties defined at all. By the way, this state comes close to the current json schema in the repository, which also defines lists instead of the classes themselves.

If I keep the name of the Rect as URL, and instead remove the `<<(T,orchid)>>` markings from the classes, I still have the broken image, but the generated JSON almost makes sense:
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",

	"id": "URL",
	"type": "object",
	"required": ["scheme"],
	"anyOf": [
		{ "$ref": "#/UserURL" },
		{ "$ref": "#/UserGUIDURL" },
		{ "$ref": "#/UserAccountURL" },
		{ "$ref": "#/HypertyURL" },
		{ "$ref": "#/HypertyCatalogueURL" },
		{ "$ref": "#/HypertyRuntimeURL" },
		{ "$ref": "#/CommunicationURL" },
		{ "$ref": "#/ConnectionURL" },
		{ "$ref": "#/DomainURL" },
		{ "$ref": "#/ContextURL" }
	]
	,
	"properties": {
		"scheme": {
			"type": "string"
		},
		"username": {
			"type": "string"
		},
		...
	}, 
	"UserURL": {
		"type": "object",
		"required": ["scheme"],
		"properties": {
			"scheme": {
				"constant": "user"
			}
		}
	},
	...
}
```
But there still is the problem that the subclasses of URL are not defined as subclasses of URL, but instead URL is "anyOf" its subclasses, which is not very useable for validation purposes.

So neither of the three approaches create sensible (although arguably "valid" schemas) when using the parser. I'm still in the process of wrapping my head around what exactly the problem is, if it is the broken schema, the json parser, or the combination of both.

I can see that the [image used for the documentation](https://github.com/reTHINK-project/dev-service-framework/blob/master/docs/datamodel/core/address/Address-Model.png) seems to be properly generated, but why is the corresponding schema in the repository in a completely different state?

The schemas have been left in this broken state for over 4 months.

**Comment by pchainho** [comment]
Sorry, @Endebert , in my comment [above](#issuecomment-236528357) I wanted to say "Message" not "URL". Regarding the URL schema we had some time ago an internal discussion and by that time we've concluded it would be difficult to validate "URL" with the json-schema and, as far as I remember, we've replaced the type "URL" by "string" from other models.

But if you find a way to use it that would be great.

**Comment by emmelmann-fokus** [comment]
Just from a birds-eye-perspective, I would conclude that the current established toolchain or the existing schemas do not allow for validation, right?

Based on @Endebert statement
> After further evaluation of the schemas and their generated json counterparts, it seems most issues I have with them come from improperly defined schemas, which then get converted into unusable json schemas.
I would say that we *have means of validation* established; the validation fails which is a valid outcome for the task taken.

@pchainho : So do we go back to fixing the defined schemas as such that they can be automatically converted into usable json schemas?  If so, this task has to be done by involving all partners as it is not part of the work item "validation".  If not, we should just stop the validation activities here.

**Comment by Endebert** [comment]
@emmelmann-fokus The problems go beyond the schemas themselves, unfortunately. As I have noted here https://github.com/reTHINK-project/dev-service-framework/issues/53#issuecomment-237287966, the parser tool created to convert the class diagrams to json schemas is not very mature in its current state, and instead of improving the tool, the class diagrams (schemas) have been modified so the tool can create sensible output. However, this results in very confusing class diagrams. 

But as you have correctly stated, the means of validation have been established. I have also found a tool that bundles the json schemas in a way that can be used for validation (i.e. resolving references to other files), and will add it as a gulp task.

@pchainho The message schema also has its problems. If I take a look at the [current state](https://raw.githubusercontent.com/reTHINK-project/dev-service-framework/develop/docs/datamodel/core/message/Message-Data-Model.png), I'm assuming it is incorrect, because any message object of any type would be valid without providing a body. So a response message is valid if it doesn't contain a response?

So in order to do (proper) validation, I have to:

1. validate the message against the generic message object schema
2. check if it has a body parameter, and fail validation if not
3. validate the message body against the correct message body schema
    * extract the message body class from the schema
    * validate the message body against that part of the schema

This is very cumbersome and more of a workaround than a solution.

Instead, similar to the different CatalogueObject types, there should be a file for each Message class (i.e. ExecuteMessage, CreateMessage, etc.), that inherits all properties from the Message class. This schema can then be used for validation, like this:
```
import responseMessageSchema from '../schemas/json-schema/core/ResponseMessage.json'
...
responseMessage = messageFactory.createMessageResponse(...)
responseMessage.validate(responseMessageSchema)
```

Unfortunately, I currently do not have enough time anymore to manually create all the json schemas the way they need to be, so progress on this will be on hold for now. But to summarize: Both the schemas and the plantuml-json-parser need to be reworked if the json parser is supposed to be used in the end. Adapting the schemas so that the json parser kind of works is _not_ a viable solution.

**Comment by Endebert** [comment]
Since we're nearing the end of the project, I'm closing all spec related issues, like this one.
