### ISSUE TITLE
Identity Manager - Discover user registered

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-service-framework#43]
When I invoke the method [discoverUserRegistered](https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/identityManager/IdentityManager.js#L52) I always have a message 'No user was not found'.

**Comment by vitormsilva** [comment]
I update the msg-node-vertx and domain-registry and it is working.

I have one more doubt, the response it is like `user://gmail.com/openidtest10` don't be something like the infoToken inside the `message.body.identity`?
example:

```json
{
"iss":"https://accounts.google.com",
"at_hash":"EgaYSTX7F55wzeiESeoWAQ",
"aud":"808329566012-tqr8qoh111942gd2kg007t0s8f277roi.apps.googleusercontent.com",
"sub":"111934233632520077743",
"email_verified":"true",
"azp":"808329566012-tqr8qoh111942gd2kg007t0s8f277roi.apps.googleusercontent.com",
"email":"openidtest10@gmail.com",
"iat":"1464360255",
"exp":"1464363855",
"name":"test OpenID",
"given_name":"test",
"family_name":"OpenID",
"locale":"pt-PT",
"alg":"RS256",
"kid":"ba1b3ecbf5f87c50b6ef15f1bb50a8c13f17a497"
}
```

**Comment by gamdias** [comment]
That method now returns a JSON with the information  "userProfile" from this specs.
https://github.com/reTHINK-project/dev-service-framework/tree/master/docs/datamodel/core/user-identity

If more information is needed, it can be added.

**Comment by vitormsilva** [comment]
Hi, I don't know if I need to update the domain-registry and msg-node-vertx again, but I can't get that, only obtaining the `user://gmail.com/openidtest10` for example.

The "userProfile" doesn't have the avatar/picture yet.

**Comment by vitormsilva** [comment]
this problem was solved.
