### ISSUE TITLE
RuntimeCatalogue.js not compatible with Nodejs Environment 

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-service-framework#46]
Trying to resolve the issue we have come with in [reTHINK-project/dev-runtime-core, issue #90](https://github.com/reTHINK-project/dev-runtime-core/issues/90), we found that in the _**dev-service-framework/dist/RuntimeCatalogue.js**_.Particularly, in the _**PersistanceManager.js**_, there is a notion of **localStorage**, which seems to be incompatible Nodejs.

**Comment by Endebert** [comment]
I'm not the one who implemented the PersistanceManager, but localStorage is imported from an npm dependency called [`universal-storage`, which is supposed to provide localStorage both in browser and nodejs](https://github.com/eddiemoore/universal-localstorage). Could you please check if this nodejs module is installed? The dependency is present in the package.json of dev-service-framework, but not in dev-runtime-core, so maybe that is the problem.

**Comment by jboulmal** [comment]
thanks for the replay, I have checked universal-storage It is already there, since we used the _**Runtime Catalogue**_ from **dev-service-framework/dist/RuntimeCatalogue.js** . we still get :_**TypeError: u.existsSync is not a function**_ at ~/dev-runtime-nodejs/dev-service framework/dist/RuntimeCatalogue.js:28:616.

**Comment by Endebert** [comment]
Sorry to hear that, hopefully @dvilchez can help you, I think he believe the PersistenceManager.

**Comment by jboulmal** [comment]
Thanks,
Alright than, I'll get in touch with him.

**Comment by jboulmal** [comment]
Coming back to this issue, we have found that the problem lies in RuntimeFactory.js importing ['service-framework/dist/RuntimeCatalogue'](https://github.com/reTHINK-project/dev-runtime-browser/blob/master/src/RuntimeFactory.js#L26), we have been able to overcome this issue using bablel transpiler on `'./node_modules/service-framework/src/RuntimeCatalogue'`, and we import the transpiled from the /dist/ folder, the good news is that it works.
