### ISSUE TITLE
IdentityManager should reject promise or return nothing, if no user information was found

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-service-framework#48]
If discoverUserRegistered is called and no user information was found, i.e. registry returns with "No information could be found", the IdentityManager should not return this string, and instead either reject the promise or resolve it without anything.

In the code I see that the IdentityManager doesn't check the message code when handling the reply, which might be the reason for this problem. However, if the registry returns the string "No information could be found" with the code 200, it should be changed to use an error code in such case instead.

**Comment by gamdias** [comment]
Thanks for the bug detection.

The IdentityManager lib now throws reject, when no user is found.

If you see any other bug or problem, please open the issue and report :)
