### ISSUE TITLE
Modification request on dev-service-framework for node

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-service-framework#49]
The following modification concerns the [RuntimeCatalogue-Local.js#L97 ](https://github.com/reTHINK-project/dev-service-framework/blob/master/src/runtime-catalogue/RuntimeCatalogue-Local.js#L97).
In order to proceed forward in `#dev-runtime-nodejs` we have simply commented this line.
`//let descriptor = createFunc(_this, result);`
Does this have side effects on what comes after ?
We invite anyone that gives his or her input on this issue, to try to reproduce it on  [#dev-runtime-nodejs/tree/child-process](https://github.com/reTHINK-project/dev-runtime-nodejs/tree/child-process).

After cloning this repository ,just run the following commands(on root): 
`1- npm install`
`2- npm start`

**Comment by jboulmal** [comment]
After careful inspection on RuntimeCatalogue.js, we have found a bug in [RuntimeCatalogue.js#L409](https://github.com/reTHINK-project/dev-service-framework/blob/master/src/runtime-catalogue/RuntimeCatalogue.js#L409). Apparently, ` sp["sourceCode"] = atob(sp["sourceCode"]);` used in `RuntimeCatalogue.js` to Decode a base-64 into encoded string is not compatible nodejs.

**Comment by Endebert** [comment]
There a module for this: https://www.npmjs.com/package/atob

Could this be added as a dependency and made globally available?

Otherwise we have to give the RuntimeCatalogue access to this function somehow, maybe similar to how httprequest is made available.

**Comment by vitormsilva** [comment]
> After careful inspection on RuntimeCatalogue.js, we have found a bug in RuntimeCatalogue.js#L409. Apparently, sp["sourceCode"] = atob(sp["sourceCode"]); used in RuntimeCatalogue.js to Decode a base-64 into encoded string is not compatible nodejs.

Yes is true, but we could do some changes, like in the runtimeFactory of nodejs or browser, we could pass the the specific implementation like [this](https://github.com/reTHINK-project/dev-runtime-nodejs/blob/nodejs-service-framework/src/RuntimeFactory.js#L48);
The module suggested by @Endebert is used on the nodejs-service-framework branch;

Regarding the first comment, why the implementation you comment doesn't work?

**Comment by jboulmal** [comment]
Thank you @vitormsilva and @Endebert for your feedbacks. We will try both aprocahes`RuntimeFactory` and module [(`https://www.npmjs.com/package/atob`)](https://www.npmjs.com/package/atob) . Concerning your last question, if we comment that line, it works. However, we don't execute the callback[`let descriptor = createFunc(_this, result);`](https://github.com/reTHINK-project/dev-service-framework/blob/master/src/runtime-catalogue/RuntimeCatalogue-Local.js#L97) .Therefore  we stay in the RuntimeCatalogue-Local.js. Adopting this last solution, introduices a changes on the service framework then. which must be independente from any implementation.

**Comment by jboulmal** [comment]
We have tried the modifications, we get the following error :

```~/dev-runtime-nodejs/dist/runtime-catalogue/RuntimeCatalogue.js:33
        _this.atob = runtimeFactory.atob ? runtimeFactory.atob : atob;
        ReferenceError: atob is not defined
```
in [RuntimeCatalogue.js#L14](https://github.com/reTHINK-project/dev-service-framework/blob/service-framework-nodejs/src/runtime-catalogue/RuntimeCatalogue.js#L14)

**Comment by jboulmal** [comment]
We have good news, it works. We can close this issue.
