### ISSUE TITLE
RuntimeCatalogue Illegal invocation

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-service-framework#52]
Since commit 4389ce59fe48f26814eec77cdbeb2f458e83c92d runtime catalog is failing with this error:

<img width="759" alt="screen-shot-2016-07-22-09-31-29" src="https://cloud.githubusercontent.com/assets/153025/17049698/1beab798-4fef-11e6-85d6-556560f07506.png">

**Comment by vitormsilva** [comment]
The runtime catalogue had a change to be compatible with node js base64 decode.
Was added to the [runtime catalogue](https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/runtime-catalogue/RuntimeCatalogue.js#L13) the following:

```javascript
_this.atob = runtimeFactory.atob ? runtimeFactory.atob : atob;
```
I think if you add the following to the RuntimeFactory of runtime-browser, should work and solve the problem:
```javascript
const RuntimeFactory = Object.create({
    //....
    atob(b64) {
      return atob(b64);
    },
    //...
});
```

**Comment by dvilchez** [comment]
Added
