### ISSUE TITLE
Failure karma tests

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-service-framework#68]
We will activate the [travis-ci.com](https://travis-ci.com), and in order to do the release, this repository has some failed tests which should be fixed.

@Endebert 
```shell
CatalogueDataObjectFactory
    constructor()
```
@gamdias:
```
IdentityManager
    discoverUserRegistered()
```
@Endebert 
I know which this test was failing because need the catalogue-broker and catalogue-database running locally, but we have 2 points:
- the "FirstHyperty", "FirstProtostub", "FirstRuntime" don't exists anymore, or exist?
- we suggest create a db with the "FirstHyperty", "FirstProtostub", "FirstRuntime" like we have before but only for the tests environment, where can be deployed through the docker-hub into travis. 
What do you think?

I created a new branch for fix this: https://github.com/reTHINK-project/dev-service-framework/tree/add-travis where i added the .travis.yml configuration file, isn't finish yet;

**Comment by gamdias** [comment]
The identityManager tests were fixed.

**Comment by vitormsilva** [comment]
@Endebert, could you fix the karma tests for CatalogueDataObjectFactory, it's only one test.

you could check here: https://travis-ci.org/reTHINK-project/dev-service-framework/jobs/172882458

**Comment by Endebert** [comment]
Will be solved as part of solving https://github.com/reTHINK-project/dev-service-framework/issues/63

**Comment by pchainho** [comment]
humm these are new features for phase 2. We are talking about a release that is pending for weeks ...

**Comment by Endebert** [comment]
Just pushed a change to the CatalogueDataObjectFactory and its test file. Please check if this stops the karma tests from failing, I can't test it locally.

**Comment by vitormsilva** [comment]
Thank you @Endebert,
Is fixed now.. https://travis-ci.org/reTHINK-project/dev-service-framework/builds/172955907

Closing issue
