### ISSUE TITLE
Runtime Catalogue: get list of available catalogue objects per type

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#75]
This is required, at least, to dynamically provide in the IDM GUI Admin, available IDP Proxies. Currently this is hardcoded

**Comment by emmelmann-fokus** [comment]
should be resolved by commit https://github.com/reTHINK-project/dev-service-framework/commit/e7f7bbd999a8b05dea4156e01dbad6ae89c157f6
