### ISSUE TITLE
Filter Catalogue Objects according to RuntimeCapabilities

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#76]
see reTHINK-project/specs#13

**Comment by Endebert** [comment]
Just FYI, progress on the Catalogue side is going well, I'd say roughly 2 more weeks until both parts are done (Catalogue & RuntimeCatalogue). I will push an updated version of RuntimeCatalogue with the adapted functions into a new branch, so that you already have something to implement against.

**Comment by pchainho** [comment]
@dvilchez has already provided that implementation

**Comment by dvilchez** [comment]
Yes, in here https://github.com/reTHINK-project/dev-runtime-browser/commit/c3f74007f464107ef8ff7bb1e1566986128fe1d5

**Comment by emmelmann-fokus** [comment]
closing this issue then.
