### ISSUE TITLE
httpRequests : update to support post with payload

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#77]
Required by [Runtime Catalogue to get constrained catalogue objects](https://github.com/reTHINK-project/dev-service-framework/issues/76)

**Comment by dvilchez** [comment]
Updated on runtime-browser#develop c3f74007f464107ef8ff7bb1e1566986128fe1d5

**Comment by jboulmal** [comment]
Done here https://github.com/reTHINK-project/dev-runtime-nodejs/blob/capabilities/src/Request.js

**Comment by jboulmal** [comment]
Done  [here](https://github.com/reTHINK-project/dev-runtime-nodejs/blob/capabilities/src/Request.js#L68), but hasn't been tested yet!

**Comment by jboulmal** [comment]
We have used the [node-fetch](https://github.com/bitinn/node-fetch) for `GET` and `POST` methods. Thus, it should work.

**Comment by pchainho** [comment]
I understand it is working fine.reopen if needed
