### ISSUE TITLE
Storage Manager: Backup Service support

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#79]
As specified [here](https://github.com/reTHINK-project/specs/issues/23)

**Comment by dvilchez** [comment]
Some doubts:

- Create syncher on StoageManager. To create a syncher I need the domain, the hypertyURL, the target hypertyURL, the bus and the configuration. Could you state what are the right values for these params.

- Add a DataItem. 

> extend storageManager.set(..) with "backupAuthorised : userURL[]" 

I guess each value could have its own backupAuthorised configuration. Where in the Databackup object can I set up this param?

- Resume the Dataobject sync. The url you link is broken.

/cc @pchainho

**Comment by pchainho** [comment]
A short term solution is to use [dexie sync server](https://www.npmjs.com/package/sync-server)
