### ISSUE TITLE
Reject error and resolve successful messages

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-service-framework#89]
In https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/discovery/Discovery.js#L192 when the search returns an empty list the discovery throws an error. IMHO this is wrong an empty list is not an error and require library users handle an empty list like an exception.

On the other hand, error messages are resolved and the original message is returned.

**Comment by BernardoMG** [comment]
Hi @dvilchez.

All discover methods returns a error when was not possible to discover something ( "Not Found"). Currently, I'm refactoring the discovery lib to support the integration with Core Discovery and I'm following these specs : https://github.com/reTHINK-project/specs/blob/master/messages/discovery-messages.md

As you can see, when the discover method finds something (Hyperty/DO) return it, but when was not possible to discover (regardless of reason) return an error with the message "Not found" and library users  should handle the exception.

If we agree to change the specs, now would be a great opportunity.

**Comment by dvilchez** [comment]
Hi @BernardoMG,

I've updated to last version of registry domain and now it returns a 404 error for not found the result. Anyway, the problem with your code is it doesn't have into account the code in the response to resolve or reject the promise.

**Comment by BernardoMG** [comment]
Ok, good. I didn't work on that version of the discovery lib. I'm working on another branch that already takes into the account HTTP response codes. Probably today or tomorrow I'll commit the changes.

So, can I close this issue @dvilchez ?

**Comment by dvilchez** [comment]
Yes, sure!
