### ISSUE TITLE
Stored assertions

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-service-framework#91]
There is no way to set en expiration time for stored assertion.

**Comment by pchainho** [comment]
duplicated with [this one](https://github.com/reTHINK-project/dev-runtime-core/issues/163) ?

**Comment by tiagolb** [comment]
@dvilchez what do you mean set expiration time? The expiration time is set by the IdP, not by "us".

**Comment by tiagolb** [comment]
@dvilchez can you please explain this issue more clearly?

Thanks

**Comment by tiagolb** [comment]
This issue has been closed [here](https://github.com/reTHINK-project/dev-runtime-core/issues/163)
